//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spacebuilder.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spacebuilder.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用{0}登录了网站“{1}”{2}.
        /// </summary>
        public static string AccountBinding_ShareToFirend {
            get {
                return ResourceManager.GetString("AccountBinding_ShareToFirend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频道.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被管理员惩罚.
        /// </summary>
        public static string Common_AdminPunish {
            get {
                return ResourceManager.GetString("Common_AdminPunish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被管理员奖励.
        /// </summary>
        public static string Common_AdminReward {
            get {
                return ResourceManager.GetString("Common_AdminReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匿名用户.
        /// </summary>
        public static string Common_AnonymousDisplayName {
            get {
                return ResourceManager.GetString("Common_AnonymousDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前天.
        /// </summary>
        public static string Common_BeforeYesterday {
            get {
                return ResourceManager.GetString("Common_BeforeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Common_BrowserTitleSeparator {
            get {
                return ResourceManager.GetString("Common_BrowserTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ：.
        /// </summary>
        public static string Common_Colon {
            get {
                return ResourceManager.GetString("Common_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Common_DateTimeWhenZero {
            get {
                return ResourceManager.GetString("Common_DateTimeWhenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string Common_DefaultDateFormat {
            get {
                return ResourceManager.GetString("Common_DefaultDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string Common_DefaultTimeFormat {
            get {
                return ResourceManager.GetString("Common_DefaultTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常URL：{0}.
        /// </summary>
        public static string Common_ExceptionUrl {
            get {
                return ResourceManager.GetString("Common_ExceptionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        public static string Common_He {
            get {
                return ResourceManager.GetString("Common_He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http传输方式：{0}.
        /// </summary>
        public static string Common_HttpMethod {
            get {
                return ResourceManager.GetString("Common_HttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在.
        /// </summary>
        public static string Common_Now {
            get {
                return ResourceManager.GetString("Common_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Common_NumberWhenZero {
            get {
                return ResourceManager.GetString("Common_NumberWhenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;&amp;lt;.
        /// </summary>
        public static string Common_PagerFirstButton {
            get {
                return ResourceManager.GetString("Common_PagerFirstButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;gt;&amp;gt;.
        /// </summary>
        public static string Common_PagerLastButton {
            get {
                return ResourceManager.GetString("Common_PagerLastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string Common_PagerNextButton {
            get {
                return ResourceManager.GetString("Common_PagerNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string Common_PagerPreviousButton {
            get {
                return ResourceManager.GetString("Common_PagerPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}月{1}日{2}.
        /// </summary>
        public static string Common_Pattern_CNMonthDay {
            get {
                return ResourceManager.GetString("Common_Pattern_CNMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}天之前.
        /// </summary>
        public static string Common_Pattern_DayAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}小时之前.
        /// </summary>
        public static string Common_Pattern_HoursAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}分钟之前.
        /// </summary>
        public static string Common_Pattern_MinutelAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_MinutelAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}秒之前.
        /// </summary>
        public static string Common_Pattern_SecondsAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分交易.
        /// </summary>
        public static string Common_PointTrade {
            get {
                return ResourceManager.GetString("Common_PointTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 惩罚用户.
        /// </summary>
        public static string Common_PunishUser {
            get {
                return ResourceManager.GetString("Common_PunishUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖励用户.
        /// </summary>
        public static string Common_RewardUser {
            get {
                return ResourceManager.GetString("Common_RewardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 她.
        /// </summary>
        public static string Common_She {
            get {
                return ResourceManager.GetString("Common_She", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta.
        /// </summary>
        public static string Common_Ta {
            get {
                return ResourceManager.GetString("Common_Ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今天.
        /// </summary>
        public static string Common_TodayAt {
            get {
                return ResourceManager.GetString("Common_TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易税.
        /// </summary>
        public static string Common_TransactionTax {
            get {
                return ResourceManager.GetString("Common_TransactionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户代理信息：{0}.
        /// </summary>
        public static string Common_UserAgent {
            get {
                return ResourceManager.GetString("Common_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户IP：{0}.
        /// </summary>
        public static string Common_UserIP {
            get {
                return ResourceManager.GetString("Common_UserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昨天.
        /// </summary>
        public static string Common_YesterdayAt {
            get {
                return ResourceManager.GetString("Common_YesterdayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有足够的访问权限.
        /// </summary>
        public static string Exception_AccessDenied {
            get {
                return ResourceManager.GetString("Exception_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有管理{0}的权限.
        /// </summary>
        public static string Exception_BasicManagementAccessDenied {
            get {
                return ResourceManager.GetString("Exception_BasicManagementAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{0}”不存在或已被删除，Id:{1}.
        /// </summary>
        public static string Exception_ContentNotFound {
            get {
                return ResourceManager.GetString("Exception_ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮件时产生异常{0}.
        /// </summary>
        public static string Exception_EmailUnableToSend {
            get {
                return ResourceManager.GetString("Exception_EmailUnableToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不允许频繁发帖.
        /// </summary>
        public static string Exception_FloodDenied {
            get {
                return ResourceManager.GetString("Exception_FloodDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到合法的Spacebuilder授权文件，请确保Web目录下存在后缀为lic的合法授权文件；如果您是商业客户，请到 http://www.jinhusns.com/Products/Contact 联系我们.
        /// </summary>
        public static string Exception_LicenseAuthorizeDenied {
            get {
                return ResourceManager.GetString("Exception_LicenseAuthorizeDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有发布{0}的权限.
        /// </summary>
        public static string Exception_PostAccessDenied {
            get {
                return ResourceManager.GetString("Exception_PostAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有进行回复的权限.
        /// </summary>
        public static string Exception_PostReplyAccessDenied {
            get {
                return ResourceManager.GetString("Exception_PostReplyAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止注册.
        /// </summary>
        public static string Exception_RegisterDenied {
            get {
                return ResourceManager.GetString("Exception_RegisterDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O或无访问权限引发的异常.
        /// </summary>
        public static string Exception_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Exception_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        public static string Exception_UnknownError {
            get {
                return ResourceManager.GetString("Exception_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户“{0}”不存在或已被删除.
        /// </summary>
        public static string Exception_UserNotFound {
            get {
                return ResourceManager.GetString("Exception_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备制造厂商.
        /// </summary>
        public static string EXIFLabel_0x10F {
            get {
                return ResourceManager.GetString("EXIFLabel_0x10F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机型号.
        /// </summary>
        public static string EXIFLabel_0x110 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曝光时间.
        /// </summary>
        public static string EXIFLabel_0x829A {
            get {
                return ResourceManager.GetString("EXIFLabel_0x829A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感光度.
        /// </summary>
        public static string EXIFLabel_0x8824 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x8824", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍摄日期.
        /// </summary>
        public static string EXIFLabel_0x9003 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大光圈.
        /// </summary>
        public static string EXIFLabel_0x9205 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪光灯.
        /// </summary>
        public static string EXIFLabel_0x9209 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焦距.
        /// </summary>
        public static string EXIFLabel_0x920a {
            get {
                return ResourceManager.GetString("EXIFLabel_0x920a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宽度.
        /// </summary>
        public static string EXIFLabel_0xa002 {
            get {
                return ResourceManager.GetString("EXIFLabel_0xa002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度.
        /// </summary>
        public static string EXIFLabel_0xa003 {
            get {
                return ResourceManager.GetString("EXIFLabel_0xa003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金币.
        /// </summary>
        public static string GoldCoin {
            get {
                return ResourceManager.GetString("GoldCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 群组空间.
        /// </summary>
        public static string GroupSpace {
            get {
                return ResourceManager.GetString("GroupSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱已被占用&amp;lt;a href=&amp;quot;{0}&amp;quot;&amp;gt;[忘记密码？]&amp;lt;/a&amp;gt;.
        /// </summary>
        public static string Message_Pattern_RegisterFailedForDuplicateEmailAddress {
            get {
                return ResourceManager.GetString("Message_Pattern_RegisterFailedForDuplicateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消激活用户.
        /// </summary>
        public static string NoActivateUser {
            get {
                return ResourceManager.GetString("NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量激活了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_ActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 设置为通过审核.
        /// </summary>
        public static string OperationLog_Pattern_Approved {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依据规则自动取消管制了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_AutoNoModeratedUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_AutoNoModeratedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封禁了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_BanUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量取消激活了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_CancelActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 取消精华.
        /// </summary>
        public static string OperationLog_Pattern_CancelEssential {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量取消管制了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_CancelModerateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelModerateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 取消置顶.
        /// </summary>
        public static string OperationLog_Pattern_CancelSticky {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看了 {0}：{1}.
        /// </summary>
        public static string OperationLog_Pattern_ControlledView {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ControlledView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建了 {0}：{1}.
        /// </summary>
        public static string OperationLog_Pattern_Create {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了 {0}：{1}.
        /// </summary>
        public static string OperationLog_Pattern_Delete {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了用户.
        /// </summary>
        public static string OperationLog_Pattern_DeleteUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 设置为未通过审核.
        /// </summary>
        public static string OperationLog_Pattern_Disapproved {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量管制了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_ModerateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ModerateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消激活用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_NoActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对用户： {0}重设了密码.
        /// </summary>
        public static string OperationLog_Pattern_ResetPassword {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖惩了用户：{0}.
        /// </summary>
        public static string OperationLog_Pattern_RewardAndPunishUsers {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_RewardAndPunishUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 由 {2} 设置为 {3}.
        /// </summary>
        public static string OperationLog_Pattern_SetCategory {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 设置为精华.
        /// </summary>
        public static string OperationLog_Pattern_SetEssential {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把 {0}：{1} 设置为置顶.
        /// </summary>
        public static string OperationLog_Pattern_SetSticky {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解禁了用户： {0}.
        /// </summary>
        public static string OperationLog_Pattern_UnbanUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_UnbanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新了 {0}：{1}.
        /// </summary>
        public static string OperationLog_Pattern_Update {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活用户.
        /// </summary>
        public static string OperationType_ActivateUser {
            get {
                return ResourceManager.GetString("OperationType_ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过审核.
        /// </summary>
        public static string OperationType_Approved {
            get {
                return ResourceManager.GetString("OperationType_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封禁用户.
        /// </summary>
        public static string OperationType_BanUser {
            get {
                return ResourceManager.GetString("OperationType_BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消设置精华.
        /// </summary>
        public static string OperationType_CancelEssential {
            get {
                return ResourceManager.GetString("OperationType_CancelEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消设置精华.
        /// </summary>
        public static string OperationType_CancelSticky {
            get {
                return ResourceManager.GetString("OperationType_CancelSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        public static string OperationType_Create {
            get {
                return ResourceManager.GetString("OperationType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string OperationType_Delete {
            get {
                return ResourceManager.GetString("OperationType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除用户.
        /// </summary>
        public static string OperationType_DeleteUser {
            get {
                return ResourceManager.GetString("OperationType_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不通过审核.
        /// </summary>
        public static string OperationType_Disapproved {
            get {
                return ResourceManager.GetString("OperationType_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消激活用户.
        /// </summary>
        public static string OperationType_NoActivateUser {
            get {
                return ResourceManager.GetString("OperationType_NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖惩用户.
        /// </summary>
        public static string OperationType_RewardAndPunishUsers {
            get {
                return ResourceManager.GetString("OperationType_RewardAndPunishUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置精华.
        /// </summary>
        public static string OperationType_SetEssential {
            get {
                return ResourceManager.GetString("OperationType_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string OperationType_SetSticky {
            get {
                return ResourceManager.GetString("OperationType_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解禁用户.
        /// </summary>
        public static string OperationType_UnbanUser {
            get {
                return ResourceManager.GetString("OperationType_UnbanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string OperationType_Update {
            get {
                return ResourceManager.GetString("OperationType_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新用户.
        /// </summary>
        public static string OperationType_UpdateUser {
            get {
                return ResourceManager.GetString("OperationType_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 通过审核.
        /// </summary>
        public static string PointRecord_Pattern_Approved {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建了 {0}：{1}.
        /// </summary>
        public static string PointRecord_Pattern_Create {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}评论了:{1}.
        /// </summary>
        public static string PointRecord_Pattern_CreateComment {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}成功邀请了用户{1}注册.
        /// </summary>
        public static string PointRecord_Pattern_CreateInviteFriendRecord {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_CreateInviteFriendRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了 {0}：{1}.
        /// </summary>
        public static string PointRecord_Pattern_Delete {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}删除了评论：{1}.
        /// </summary>
        public static string PointRecord_Pattern_DeleteComment {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}邀请的用户{1}被删除了.
        /// </summary>
        public static string PointRecord_Pattern_DeleteInvitedUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_DeleteInvitedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 未通过审核.
        /// </summary>
        public static string PointRecord_Pattern_Disapproved {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首次上传头像.
        /// </summary>
        public static string PointRecord_Pattern_FirstUploadAvatar {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FirstUploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注了用户&quot;{0}&quot;.
        /// </summary>
        public static string PointRecord_Pattern_FollowUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FollowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}邀请的用户{1}成功解除了管制.
        /// </summary>
        public static string PointRecord_Pattern_FreeModeratedUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FreeModeratedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反对了{0}.
        /// </summary>
        public static string PointRecord_Pattern_Oppose {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Oppose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 被管理员推荐.
        /// </summary>
        public static string PointRecord_Pattern_RecommendContent {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_RecommendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您被管理员推荐.
        /// </summary>
        public static string PointRecord_Pattern_RecommendUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_RecommendUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}注册了帐号.
        /// </summary>
        public static string PointRecord_Pattern_Register {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 被管理员设置为精华.
        /// </summary>
        public static string PointRecord_Pattern_SetEssential {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 被管理员设置为栏目置顶.
        /// </summary>
        public static string PointRecord_Pattern_SetFolderSticky {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetFolderSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 被管理员设置为整站置顶.
        /// </summary>
        public static string PointRecord_Pattern_SetGlobalSticky {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetGlobalSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} 被管理员设置为置顶.
        /// </summary>
        public static string PointRecord_Pattern_SetSticky {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赞同了{0}.
        /// </summary>
        public static string PointRecord_Pattern_Support {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户空间.
        /// </summary>
        public static string UserSpace {
            get {
                return ResourceManager.GetString("UserSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}无效.
        /// </summary>
        public static string Validate_DateType {
            get {
                return ResourceManager.GetString("Validate_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入电子邮箱.
        /// </summary>
        public static string Validate_EmailRequired {
            get {
                return ResourceManager.GetString("Validate_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱格式不正确，请输入正确格式的邮箱地址.
        /// </summary>
        public static string Validate_EmailStyle {
            get {
                return ResourceManager.GetString("Validate_EmailStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法昵称.
        /// </summary>
        public static string Validate_NickNameHasSensitiveWord {
            get {
                return ResourceManager.GetString("Validate_NickNameHasSensitiveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称不允许使用，请选择其他昵称后注册.
        /// </summary>
        public static string Validate_NickNameIsDisallowed {
            get {
                return ResourceManager.GetString("Validate_NickNameIsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该昵称已被占用，请更换其他昵称重试.
        /// </summary>
        public static string Validate_NickNameIsExisting {
            get {
                return ResourceManager.GetString("Validate_NickNameIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能输入字母、数字、汉字和下划线.
        /// </summary>
        public static string Validate_NickNameRegex {
            get {
                return ResourceManager.GetString("Validate_NickNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入昵称.
        /// </summary>
        public static string Validate_NickNameRequired {
            get {
                return ResourceManager.GetString("Validate_NickNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称长度最多{0}位.
        /// </summary>
        public static string Validate_NickNameTooLong {
            get {
                return ResourceManager.GetString("Validate_NickNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称长度不能少于{0}位.
        /// </summary>
        public static string Validate_NickNameTooShort {
            get {
                return ResourceManager.GetString("Validate_NickNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}必须是数字.
        /// </summary>
        public static string Validate_NumericInvalid {
            get {
                return ResourceManager.GetString("Validate_NumericInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您输入的密码格式不正确.
        /// </summary>
        public static string Validate_PasswordRegex {
            get {
                return ResourceManager.GetString("Validate_PasswordRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的密码中特殊字符太少，请至少输入 {0} 个特殊字符（如：*、$等）.
        /// </summary>
        public static string Validate_Pattern_MinRequiredNonAlphanumericCharacters {
            get {
                return ResourceManager.GetString("Validate_Pattern_MinRequiredNonAlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度不能少于 {0} 个字符.
        /// </summary>
        public static string Validate_Pattern_MinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("Validate_Pattern_MinRequiredPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该手机号已注册，请登录.
        /// </summary>
        public static string Validate_PhoneIsExisting {
            get {
                return ResourceManager.GetString("Validate_PhoneIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该手机号已注册，请登录.
        /// </summary>
        public static string Validate_PhoneIsExistingForMobileClient {
            get {
                return ResourceManager.GetString("Validate_PhoneIsExistingForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入正确的手机号.
        /// </summary>
        public static string Validate_PhoneRegex {
            get {
                return ResourceManager.GetString("Validate_PhoneRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入手机号.
        /// </summary>
        public static string Validate_PhoneRequired {
            get {
                return ResourceManager.GetString("Validate_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入手机号.
        /// </summary>
        public static string Validate_PhoneRequiredForMobileClient {
            get {
                return ResourceManager.GetString("Validate_PhoneRequiredForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}必须介于{1}和之{2}间.
        /// </summary>
        public static string Validate_Range {
            get {
                return ResourceManager.GetString("Validate_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 表达式：{1}.
        /// </summary>
        public static string Validate_RegularExpression {
            get {
                return ResourceManager.GetString("Validate_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不能为空.
        /// </summary>
        public static string Validate_Required {
            get {
                return ResourceManager.GetString("Validate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        public static string Validate_RequiredPassword {
            get {
                return ResourceManager.GetString("Validate_RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}长度要求填写{2} 至 {1} 位.
        /// </summary>
        public static string Validate_StringLength {
            get {
                return ResourceManager.GetString("Validate_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该邮箱已被占用，请更换邮箱重试.
        /// </summary>
        public static string Validate_UserEmailIsExisting {
            get {
                return ResourceManager.GetString("Validate_UserEmailIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法用户名.
        /// </summary>
        public static string Validate_UserNameHasSensitiveWord {
            get {
                return ResourceManager.GetString("Validate_UserNameHasSensitiveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法用户名.
        /// </summary>
        public static string Validate_UserNameHasSensitiveWordForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameHasSensitiveWordForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户名不允许使用，请选择其他名字后注册.
        /// </summary>
        public static string Validate_UserNameIsDisallowed {
            get {
                return ResourceManager.GetString("Validate_UserNameIsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该账号不允许使用，请选择其他名字后注册.
        /// </summary>
        public static string Validate_UserNameIsDisallowedForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameIsDisallowedForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户名已被占用，请更换用户名重试.
        /// </summary>
        public static string Validate_UserNameIsExisting {
            get {
                return ResourceManager.GetString("Validate_UserNameIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该账号已被占用，请更换账号重试.
        /// </summary>
        public static string Validate_UserNameIsExistingForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameIsExistingForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能输入字母、数字、汉字和下划线.
        /// </summary>
        public static string Validate_UserNameRegex {
            get {
                return ResourceManager.GetString("Validate_UserNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名.
        /// </summary>
        public static string Validate_UserNameRequired {
            get {
                return ResourceManager.GetString("Validate_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入账号.
        /// </summary>
        public static string Validate_UserNameRequiredForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameRequiredForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名长度最多{0}位.
        /// </summary>
        public static string Validate_UserNameTooLong {
            get {
                return ResourceManager.GetString("Validate_UserNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号长度最多{0}位.
        /// </summary>
        public static string Validate_UserNameTooLongForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameTooLongForMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名长度不能少于{0}位.
        /// </summary>
        public static string Validate_UserNameTooShort {
            get {
                return ResourceManager.GetString("Validate_UserNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号长度不能少于{0}位.
        /// </summary>
        public static string Validate_UserNameTooShortForMobileClient {
            get {
                return ResourceManager.GetString("Validate_UserNameTooShortForMobileClient", resourceCulture);
            }
        }
    }
}
